/**
 * Narrative Display Component
 * Shows AI-generated narrative events in real-time
 */

import { useEffect, useState } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import { NarrativeEvent, NarrativeAxis } from '@/game/narrative/AIStoryGenerator';
import { Brain, Zap, Leaf, Box, BookOpen, MessageSquare } from 'lucide-react';
import { cn } from '@/lib/utils';

interface NarrativeDisplayProps {
  events: NarrativeEvent[];
  maxHeight?: string;
}

const axisIcons = {
  matter: Box,
  energy: Zap,
  life: Leaf,
  knowledge: Brain
};

const axisColors = {
  matter: 'text-blue-400 border-blue-400/30 bg-blue-400/10',
  energy: 'text-yellow-400 border-yellow-400/30 bg-yellow-400/10',
  life: 'text-green-400 border-green-400/30 bg-green-400/10',
  knowledge: 'text-purple-400 border-purple-400/30 bg-purple-400/10'
};

const typeIcons = {
  lore: BookOpen,
  dialogue: MessageSquare,
  mission: Brain,
  chronicle: BookOpen,
  memory: Brain
};

export const NarrativeDisplay = ({ events, maxHeight = '400px' }: NarrativeDisplayProps) => {
  const [displayedEvents, setDisplayedEvents] = useState<NarrativeEvent[]>([]);

  useEffect(() => {
    // Animate events appearing
    if (events.length > displayedEvents.length) {
      const newEvents = events.slice(displayedEvents.length);
      newEvents.forEach((event, idx) => {
        setTimeout(() => {
          setDisplayedEvents(prev => [...prev, event]);
        }, idx * 200);
      });
    }
  }, [events, displayedEvents.length]);

  return (
    <Card className="bg-card/90 border-primary/30">
      <CardContent className="p-4">
        <ScrollArea className={cn('w-full')} style={{ maxHeight }}>
          <div className="space-y-3">
            {displayedEvents.map((event) => {
              const AxisIcon = event.axis ? axisIcons[event.axis] : Brain;
              const TypeIcon = typeIcons[event.type];
              const axisColor = event.axis ? axisColors[event.axis] : 'text-gray-400 border-gray-400/30 bg-gray-400/10';

              return (
                <div
                  key={event.id}
                  className={cn(
                    'p-3 rounded-lg border backdrop-blur-sm transition-all animate-in slide-in-from-right',
                    axisColor
                  )}
                >
                  <div className="flex items-start gap-2 mb-2">
                    {event.axis && (
                      <AxisIcon className="w-4 h-4 mt-0.5 flex-shrink-0" />
                    )}
                    <TypeIcon className="w-4 h-4 mt-0.5 flex-shrink-0" />
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="text-xs font-semibold uppercase">
                          {event.axis || 'System'} • {event.type}
                        </span>
                        {event.timeline && (
                          <span className="text-xs text-muted-foreground">
                            {event.timeline}
                          </span>
                        )}
                      </div>
                      <p className="text-sm leading-relaxed">{event.content}</p>
                      <div className="flex items-center gap-2 mt-2 text-xs text-muted-foreground">
                        <span>Generated by {event.generatedBy}</span>
                        <span>•</span>
                        <span>Tone: {event.emotionalTone}</span>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
            {displayedEvents.length === 0 && (
              <div className="text-center text-muted-foreground py-8">
                <BookOpen className="w-12 h-12 mx-auto mb-2 opacity-50" />
                <p className="text-sm">Narrative events will appear here as you play</p>
              </div>
            )}
          </div>
        </ScrollArea>
      </CardContent>
    </Card>
  );
};

