import { useState } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Brain, Zap, Leaf, Box, Mic, Music, Video, Layers, Gamepad2, Sparkles } from 'lucide-react';

interface PipelineNode {
  id: string;
  label: string;
  subtitle: string;
  icon: React.ReactNode;
  color: string;
  position: { x: number; y: number };
  connections: string[];
  description?: string;
}

const AIPipelineVisualization = () => {
  const [selectedNode, setSelectedNode] = useState<string | null>(null);
  const [hoveredNode, setHoveredNode] = useState<string | null>(null);

  const nodes: PipelineNode[] = [
    {
      id: 'user-input',
      label: 'User Input',
      subtitle: 'Player Actions',
      icon: <Gamepad2 className="w-5 h-5" />,
      color: '#21808d',
      position: { x: 50, y: 10 },
      connections: ['game-logic'],
      description: 'Player commands, unit selections, and strategic decisions'
    },
    {
      id: 'game-logic',
      label: 'Game Logic',
      subtitle: 'State Update',
      icon: <Layers className="w-5 h-5" />,
      color: '#21808d',
      position: { x: 50, y: 30 },
      connections: ['ai-evaluation'],
      description: 'Core game mechanics, resource management, and unit interactions'
    },
    {
      id: 'ai-evaluation',
      label: 'AI Evaluation',
      subtitle: 'Google Gemini 2.5',
      icon: <Brain className="w-5 h-5" />,
      color: '#21808d',
      position: { x: 50, y: 50 },
      connections: ['proc-gen', 'cmd-npc', 'narrative', 'audio'],
      description: 'Central AI coordinator analyzing game state and orchestrating responses'
    },
    {
      id: 'proc-gen',
      label: 'Procedural Gen',
      subtitle: 'Luma AI, Google AI',
      icon: <Layers className="w-5 h-5" />,
      color: '#5D878F',
      position: { x: 15, y: 70 },
      connections: ['output'],
      description: 'AI-generated maps, terrain, and procedural content using Luma AI and Google AI'
    },
    {
      id: 'cmd-npc',
      label: 'Command & NPC',
      subtitle: 'Google AI, ML',
      icon: <Brain className="w-5 h-5" />,
      color: '#5D878F',
      position: { x: 35, y: 70 },
      connections: ['output'],
      description: 'Strategic commander AI and NPC behaviors powered by Google Gemini and ML models'
    },
    {
      id: 'narrative',
      label: 'Narrative',
      subtitle: 'Saga, Google AI',
      icon: <Video className="w-5 h-5" />,
      color: '#5D878F',
      position: { x: 65, y: 70 },
      connections: ['output'],
      description: 'Dynamic storytelling and event narratives generated by Saga and Google AI'
    },
    {
      id: 'audio',
      label: 'Audio & Music',
      subtitle: '11Labs, Fuser',
      icon: <Music className="w-5 h-5" />,
      color: '#5D878F',
      position: { x: 85, y: 70 },
      connections: ['output'],
      description: 'Voice narration via ElevenLabs and adaptive music from Fuser'
    },
    {
      id: 'output',
      label: 'Output Render',
      subtitle: 'Visual + Audio',
      icon: <Sparkles className="w-5 h-5" />,
      color: '#21808d',
      position: { x: 50, y: 90 },
      connections: ['player-exp'],
      description: 'Rendered game state combining all AI-generated content'
    },
    {
      id: 'player-exp',
      label: 'Player Experience',
      subtitle: 'Interactive',
      icon: <Gamepad2 className="w-5 h-5" />,
      color: '#21808d',
      position: { x: 50, y: 110 },
      connections: [],
      description: 'Final player experience with all AI enhancements integrated'
    }
  ];

  const getNodeById = (id: string) => nodes.find(n => n.id === id);

  const renderConnection = (from: PipelineNode, toId: string) => {
    const to = getNodeById(toId);
    if (!to) return null;

    const fromX = from.position.x;
    const fromY = from.position.y;
    const toX = to.position.x;
    const toY = to.position.y;

    // Calculate arrow path
    const dx = toX - fromX;
    const dy = toY - fromY;
    const angle = Math.atan2(dy, dx) * (180 / Math.PI);

    return (
      <g key={`${from.id}-${toId}`}>
        <line
          x1={`${fromX}%`}
          y1={`${fromY}%`}
          x2={`${toX}%`}
          y2={`${toY}%`}
          stroke={hoveredNode === from.id || hoveredNode === toId ? '#21808d' : '#5D878F'}
          strokeWidth={hoveredNode === from.id || hoveredNode === toId ? 3 : 2}
          strokeDasharray={hoveredNode === from.id || hoveredNode === toId ? '0' : '5,5'}
          opacity={hoveredNode === from.id || hoveredNode === toId ? 1 : 0.4}
          markerEnd="url(#arrowhead)"
          className="transition-all duration-300"
        />
      </g>
    );
  };

  return (
    <div className="w-full">
      <Card className="bg-card/70 border-primary/30">
        <CardContent className="p-6">
          <div className="mb-6">
            <h3 className="text-2xl font-bold text-primary mb-2">AI Integration Pipeline</h3>
            <p className="text-sm text-muted-foreground">
              Interactive visualization of how AI systems work together in Quaternion
            </p>
          </div>

          <div className="relative w-full" style={{ height: '600px', minHeight: '600px' }}>
            <svg
              viewBox="0 0 100 120"
              className="w-full h-full"
              style={{ position: 'absolute', top: 0, left: 0 }}
            >
              {/* Arrow marker definition */}
              <defs>
                <marker
                  id="arrowhead"
                  markerWidth="10"
                  markerHeight="10"
                  refX="9"
                  refY="3"
                  orient="auto"
                >
                  <polygon
                    points="0 0, 10 3, 0 6"
                    fill="#21808d"
                    className="transition-colors duration-300"
                  />
                </marker>
              </defs>

              {/* Render all connections */}
              {nodes.map(node =>
                node.connections.map(connId => renderConnection(node, connId))
              )}

              {/* Render nodes */}
              {nodes.map((node) => {
                const isSelected = selectedNode === node.id;
                const isHovered = hoveredNode === node.id;
                const isActive = isSelected || isHovered;

                return (
                  <g
                    key={node.id}
                    transform={`translate(${node.position.x}, ${node.position.y})`}
                    onMouseEnter={() => setHoveredNode(node.id)}
                    onMouseLeave={() => setHoveredNode(null)}
                    onClick={() => setSelectedNode(isSelected ? null : node.id)}
                    className="cursor-pointer"
                  >
                    {/* Node background */}
                    <rect
                      x="-8"
                      y="-4"
                      width="16"
                      height="8"
                      rx="2"
                      fill={isActive ? node.color : '#e8f4f5'}
                      stroke={node.color}
                      strokeWidth={isActive ? 3 : 2}
                      className="transition-all duration-300"
                    />

                    {/* Icon */}
                    <g transform="translate(-6, -2.5)" fill={isActive ? '#ffffff' : node.color}>
                      {node.icon}
                    </g>

                    {/* Label */}
                    <text
                      x="0"
                      y="6"
                      textAnchor="middle"
                      fontSize="2.5"
                      fill={isActive ? '#ffffff' : '#13343b'}
                      fontWeight="bold"
                      className="pointer-events-none"
                    >
                      {node.label}
                    </text>

                    {/* Subtitle */}
                    {node.subtitle && (
                      <text
                        x="0"
                        y="9.5"
                        textAnchor="middle"
                        fontSize="1.8"
                        fill={isActive ? '#e8f4f5' : '#5D878F'}
                        className="pointer-events-none"
                      >
                        {node.subtitle}
                      </text>
                    )}
                  </g>
                );
              })}
            </svg>
          </div>

          {/* Node details panel */}
          {selectedNode && (
            <div className="mt-6 p-4 bg-primary/10 rounded-lg border border-primary/30 animate-in fade-in slide-in-from-bottom-4">
              {(() => {
                const node = getNodeById(selectedNode);
                if (!node) return null;
                return (
                  <>
                    <div className="flex items-center gap-3 mb-3">
                      <div className="text-primary">{node.icon}</div>
                      <div>
                        <h4 className="font-bold text-primary text-lg">{node.label}</h4>
                        <p className="text-sm text-muted-foreground">{node.subtitle}</p>
                      </div>
                    </div>
                    {node.description && (
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        {node.description}
                      </p>
                    )}
                  </>
                );
              })()}
            </div>
          )}

          {/* Legend */}
          <div className="mt-6 grid grid-cols-2 md:grid-cols-4 gap-4 text-xs">
            <div className="flex items-center gap-2">
              <div className="w-4 h-4 rounded bg-[#21808d]"></div>
              <span className="text-muted-foreground">Core Systems</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-4 h-4 rounded bg-[#5D878F]"></div>
              <span className="text-muted-foreground">AI Services</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-4 h-4 border-2 border-[#21808d] rounded"></div>
              <span className="text-muted-foreground">Data Flow</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-4 h-4 border-2 border-dashed border-[#5D878F] rounded"></div>
              <span className="text-muted-foreground">AI Processing</span>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default AIPipelineVisualization;

