import { useState } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Brain, Music, Video, Layers, Gamepad2, Sparkles, Cpu, Mic } from 'lucide-react';

interface PipelineNode {
  id: string;
  label: string;
  subtitle: string;
  icon: React.ComponentType<{ className?: string }>;
  color: string;
  bgColor: string;
  position: { x: number; y: number };
  connections: string[];
  description?: string;
  tools?: string[];
}

const AIPipelineVisualization = () => {
  const [selectedNode, setSelectedNode] = useState<string | null>(null);
  const [hoveredNode, setHoveredNode] = useState<string | null>(null);

  const nodes: PipelineNode[] = [
    {
      id: 'user-input',
      label: 'User Input',
      subtitle: 'Player Actions',
      icon: Gamepad2,
      color: '#21808d',
      bgColor: '#e8f4f5',
      position: { x: 50, y: 5 },
      connections: ['game-logic'],
      description: 'Player commands, unit selections, and strategic decisions flow into the game system',
      tools: []
    },
    {
      id: 'game-logic',
      label: 'Game Logic',
      subtitle: 'State Update',
      icon: Layers,
      color: '#21808d',
      bgColor: '#e8f4f5',
      position: { x: 50, y: 20 },
      connections: ['ai-evaluation'],
      description: 'Core game mechanics process player actions, update resource states, and manage unit interactions',
      tools: []
    },
    {
      id: 'ai-evaluation',
      label: 'AI Evaluation',
      subtitle: 'Google AI',
      icon: Brain,
      color: '#21808d',
      bgColor: '#e8f4f5',
      position: { x: 50, y: 40 },
      connections: ['proc-gen', 'cmd-npc', 'narrative', 'audio'],
      description: 'Central AI coordinator analyzes game state and orchestrates responses across all AI systems',
      tools: ['Google AI']
    },
    {
      id: 'proc-gen',
      label: 'Procedural Gen',
      subtitle: 'Luma AI, Google AI',
      icon: Layers,
      color: '#5D878F',
      bgColor: '#f0f8f9',
      position: { x: 15, y: 60 },
      connections: ['output'],
      description: 'AI-generated maps, terrain features, and procedural content using Luma AI for 3D assets and Google AI for generation logic',
      tools: ['Luma AI', 'Google AI']
    },
    {
      id: 'cmd-npc',
      label: 'Command & NPC',
      subtitle: 'Google AI, ML',
      icon: Cpu,
      color: '#5D878F',
      bgColor: '#f0f8f9',
      position: { x: 35, y: 60 },
      connections: ['output'],
      description: 'Strategic commander AI and NPC behaviors powered by Google AI for high-level decisions and ML models for tactical behavior',
      tools: ['Google AI', 'ML Models']
    },
    {
      id: 'narrative',
      label: 'Narrative',
      subtitle: 'Saga, Google AI',
      icon: Video,
      color: '#5D878F',
      bgColor: '#f0f8f9',
      position: { x: 65, y: 60 },
      connections: ['output'],
      description: 'Dynamic storytelling and event narratives generated by Saga for scriptwriting and Google AI for contextual dialogue',
      tools: ['Saga', 'Google AI']
    },
    {
      id: 'audio',
      label: 'Audio & Music',
      subtitle: '11Labs, Fuser',
      icon: Music,
      color: '#5D878F',
      bgColor: '#f0f8f9',
      position: { x: 85, y: 60 },
      connections: ['output'],
      description: 'Voice narration via ElevenLabs TTS and adaptive music generation from Fuser that responds to game events',
      tools: ['ElevenLabs', 'Fuser']
    },
    {
      id: 'output',
      label: 'Output Render',
      subtitle: 'Visual + Audio',
      icon: Sparkles,
      color: '#21808d',
      bgColor: '#e8f4f5',
      position: { x: 50, y: 80 },
      connections: ['player-exp'],
      description: 'Rendered game state combining all AI-generated content into a cohesive visual and audio experience',
      tools: []
    },
    {
      id: 'player-exp',
      label: 'Player Experience',
      subtitle: 'Interactive',
      icon: Gamepad2,
      color: '#21808d',
      bgColor: '#e8f4f5',
      position: { x: 50, y: 95 },
      connections: [],
      description: 'Final player experience with all AI enhancements seamlessly integrated into gameplay',
      tools: []
    }
  ];

  const getNodeById = (id: string) => nodes.find(n => n.id === id);

  const renderConnection = (from: PipelineNode, toId: string) => {
    const to = getNodeById(toId);
    if (!to) return null;

    const fromX = from.position.x;
    const fromY = from.position.y;
    const toX = to.position.x;
    const toY = to.position.y;

    const isActive = hoveredNode === from.id || hoveredNode === toId;

    return (
      <line
        key={`${from.id}-${toId}`}
        x1={`${fromX}%`}
        y1={`${fromY}%`}
        x2={`${toX}%`}
        y2={`${toY}%`}
        stroke={isActive ? '#21808d' : '#5D878F'}
        strokeWidth={isActive ? 3 : 2}
        strokeDasharray={isActive ? '0' : '5,5'}
        opacity={isActive ? 1 : 0.5}
        markerEnd="url(#arrowhead)"
        className="transition-all duration-300 pointer-events-none"
      />
    );
  };

  return (
    <div className="w-full">
      <Card className="bg-card/70 border-primary/30">
        <CardContent className="p-6">
          <div className="mb-6">
            <h3 className="text-2xl font-bold text-primary mb-2">AI Integration Pipeline</h3>
            <p className="text-sm text-muted-foreground">
              Interactive visualization of how AI systems work together in Quaternion. Hover over nodes to see connections, click for details.
            </p>
          </div>

          <div className="relative w-full overflow-hidden" style={{ height: '650px', minHeight: '650px' }}>
            <svg
              viewBox="0 0 100 100"
              className="w-full h-full"
              preserveAspectRatio="xMidYMid meet"
            >
              {/* Arrow marker definition */}
              <defs>
                <marker
                  id="arrowhead"
                  markerWidth="10"
                  markerHeight="10"
                  refX="9"
                  refY="3"
                  orient="auto"
                >
                  <polygon
                    points="0 0, 10 3, 0 6"
                    fill="#21808d"
                    className="transition-colors duration-300"
                  />
                </marker>
              </defs>

              {/* Render all connections */}
              {nodes.map(node =>
                node.connections.map(connId => renderConnection(node, connId))
              )}

              {/* Render nodes */}
              {nodes.map((node) => {
                const isSelected = selectedNode === node.id;
                const isHovered = hoveredNode === node.id;
                const isActive = isSelected || isHovered;
                const IconComponent = node.icon;

                return (
                  <g
                    key={node.id}
                    transform={`translate(${node.position.x}, ${node.position.y})`}
                    onMouseEnter={() => setHoveredNode(node.id)}
                    onMouseLeave={() => setHoveredNode(null)}
                    onClick={() => setSelectedNode(isSelected ? null : node.id)}
                    className="cursor-pointer"
                  >
                    {/* Node background */}
                    <rect
                      x="-12"
                      y="-6"
                      width="24"
                      height="12"
                      rx="3"
                      fill={isActive ? node.color : node.bgColor}
                      stroke={node.color}
                      strokeWidth={isActive ? 3 : 2}
                      className="transition-all duration-300"
                    />

                    {/* Icon */}
                    <foreignObject x="-10" y="-5" width="20" height="10">
                      <div className="flex items-center justify-center h-full">
                        <IconComponent 
                          className="w-4 h-4"
                        />
                      </div>
                    </foreignObject>

                    {/* Label */}
                    <text
                      x="0"
                      y="2"
                      textAnchor="middle"
                      fontSize="2.2"
                      fill={isActive ? '#ffffff' : '#13343b'}
                      fontWeight="bold"
                      className="pointer-events-none"
                    >
                      {node.label}
                    </text>

                    {/* Subtitle */}
                    {node.subtitle && (
                      <text
                        x="0"
                        y="5"
                        textAnchor="middle"
                        fontSize="1.6"
                        fill={isActive ? '#e8f4f5' : '#5D878F'}
                        className="pointer-events-none"
                      >
                        {node.subtitle}
                      </text>
                    )}
                  </g>
                );
              })}
            </svg>
          </div>

          {/* Node details panel */}
          {selectedNode && (
            <div className="mt-6 p-4 bg-primary/10 rounded-lg border border-primary/30 animate-in fade-in slide-in-from-bottom-4">
              {(() => {
                const node = getNodeById(selectedNode);
                if (!node) return null;
                const IconComponent = node.icon;
                return (
                  <>
                    <div className="flex items-center gap-3 mb-3">
                      <div className="text-primary">
                        <IconComponent className="w-6 h-6" />
                      </div>
                      <div>
                        <h4 className="font-bold text-primary text-lg">{node.label}</h4>
                        <p className="text-sm text-muted-foreground">{node.subtitle}</p>
                      </div>
                    </div>
                    {node.description && (
                      <p className="text-sm text-muted-foreground leading-relaxed mb-3">
                        {node.description}
                      </p>
                    )}
                    {node.tools && node.tools.length > 0 && (
                      <div className="mt-3 pt-3 border-t border-primary/20">
                        <p className="text-xs font-semibold text-primary mb-2">AI Tools:</p>
                        <div className="flex flex-wrap gap-2">
                          {node.tools.map((tool, idx) => (
                            <span
                              key={idx}
                              className="text-xs px-2 py-1 bg-primary/20 text-primary rounded border border-primary/30"
                            >
                              {tool}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </>
                );
              })()}
            </div>
          )}

          {/* Legend */}
          <div className="mt-6 grid grid-cols-2 md:grid-cols-4 gap-4 text-xs">
            <div className="flex items-center gap-2">
              <div className="w-4 h-4 rounded bg-[#21808d]"></div>
              <span className="text-muted-foreground">Core Systems</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-4 h-4 rounded bg-[#5D878F]"></div>
              <span className="text-muted-foreground">AI Services</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-4 h-4 border-2 border-[#21808d] rounded"></div>
              <span className="text-muted-foreground">Data Flow</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-4 h-4 border-2 border-dashed border-[#5D878F] rounded"></div>
              <span className="text-muted-foreground">AI Processing</span>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default AIPipelineVisualization;

